m1 = Movie.create("title" => "The Dark Knight", "genre" => "action")
m2 = Movie.create("title" => "Deadpool", "genre" => "action")
m3 = Movie.create("title" => "Avengers: Endgame", "genre" => "action")
m4 = Movie.create("title" => "Terminator 2: Judgement Day", "genre" => "action")
m5 = Movie.create("title" => "Gladiator", "genre" => "action")
m6 = Movie.create("title" => "Home Alone", "genre" => "comedy")
m7 = Movie.create("title" => "The Hangover", "genre" => "comedy")
m8 = Movie.create("title" => "Ted", "genre" => "comedy")
m9 = Movie.create("title" => "Wedding Crashers", "genre" => "comedy")
m10 = Movie.create("title" => "Step Brothers", "genre" => "comedy")
m11 = Movie.create("title" => "Lady Bird", "genre" => "drama")
m12 = Movie.create("title" => "Casablanca", "genre" => "drama")
m13 = Movie.create("title" => "Manchester by the Sea", "genre" => "drama")
m14 = Movie.create("title" => "La La Land", "genre" => "drama")
m15 = Movie.create("title" => "Creed", "genre" => "drama")
m16 = Movie.create("title" => "Get Out", "genre" => "horror")
m17 = Movie.create("title" => "A Quiet Place", "genre" => "horror")
m18 = Movie.create("title" => "Frankenstein", "genre" => "horror")
m19 = Movie.create("title" => "Psycho", "genre" => "horror")
m20 = Movie.create("title" => "Halloween", "genre" => "horror")
m21 = Movie.create("title" => "Inception", "genre" => "sci-fi")
m22 = Movie.create("title" => "The Matrix", "genre" => "sci-fi")
m23 = Movie.create("title" => "E.T. The Extra-Terrestrial", "genre" => "sci-fi")
m24 = Movie.create("title" => "Back to the Future", "genre" => "sci-fi")
m25 = Movie.create("title" => "Alien", "genre" => "sci-fi")